### ISSUE TITLE
Can we Include Arduino Json lib at the beginning of ConsentiumDalton.h , whats the need for defining in every line .

### ISSUE THREAD

**Issue by MISTERNEGATIVE21** [ConsentiumInc/ConsentiumThingsDalton#2]
<img width="462" alt="image" src="https://github.com/ConsentiumInc/ConsentiumThingsDalton/assets/51168229/d914cf1e-667c-4908-9a1c-703eaa23d63c">

We can see Arduino Json being defined in every line , can we just define it globally

**Comment by ConsentiumInc** [comment]
Made changes to the included file ConsentiumDalton.h, which will be public in the next release.
